### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by ilvalle** [niphlod/cs_monitor_plugin#5]
It would be nice to see repetitive tasks shown in a calendar. I don't know how that can be difficult (right now I am thinking about full calendar).

**Comment by niphlod** [comment]
I know fullcalendar and I use it yet in w2p_tvseries, it wouldn't be that hard, but how can this be helpful ?
I mean, given that you have 5 tasks, with respectively: 
- period = 60 (1 minute)
- period = 60*5 (5 minutes)
- period = 60_60_5 (5 hours)
- period = 60_60_24 (1 day)
- period = 60_60_24*5 (5 days)

What you'd like to see ? A calendar in the "index" page with all the 5 tasks and their "presumed" run-cycle, or a calendar in the "analyze task" page, detailing for 1 task only its execution times (assuming it has a scheduler_run record) ?

**Comment by ilvalle** [comment]
For very frequent tasks I cannot see any useful advantage from the
calendar. Besides that,
To start I would see very well the calendar to have a general overview of
the situation, both past and current/future. The
task completed successfully with different colors than the others. The
calendar page should provide some kind of filters such as 'show me only
tasks belonging to that worker' or 'called as ...' and so on.
Finally, the possibility to add a new task, something that will call the
already present 'create task form'.
These are just thoughts that came to my mind, what do you think?

 Paolo

2013/3/21 niphlod notifications@github.com

**Comment by niphlod** [comment]
The quicklink to create a task is in index.html and adding that to the eventual calendar.html wouldn't be a problem

In your idea there are a lot of "besides" too look for. 
On the top of my head there are two major problems.....
- display "future" is quite a leap of faith
  - workers can die
  - tasks can fail
  - tasks can "exhaust" the repeat_failed parameter
  - etc etc etc
- display "past" is accomplished yet in the graphs of analyze task. They're grouped by task status and by day by default and you can regroup by function_name and task_name. The graphs are a nice representation of the set of data for whatever "type" of task you queued. Unfortunately a calendar view is fine for appointments or events, as long as the "finer" detail you wish gets printed and it's readable. The problem is that you may have so many overlapping tasks to render the calendar view unuseful (e.g., fullcalendar with two overlapping tasks divides the "day" cell horizontally... for 10 tasks the output would be un-easy to read)

Try to come up with a mockup or a picture, a lot of problems will come up just trying to wire up the interface. That being said, if you realize a mockup that has no issues, we can discuss it further.

**Comment by ilvalle** [comment]
I see your points about displaying several tasks in the same moment or even worst to show very frequent tasks, I can just go forward by saying we can use filter to decide what to show. 
Moreover we have two potential views: past and future.
past view is not totally described in the graph, the look&feel is not the same IMHO, with the past view, my first requirement is to understand which tasks failed. 
future view, I agree with what you have said. The future is not predictable at all but what we can at least show is the 'expected' task scheduling

**Comment by niphlod** [comment]
so, did you came up with a mockup/sketch/image of what the final result should be ?
