### ISSUE TITLE
restart a task after it has been stopped

### ISSUE THREAD

**Issue by niphlod** [niphlod/cs_monitor_plugin#9]

**Comment by ilvalle** [comment]
+1

**Comment by niphlod** [comment]
ilvalle reported:

there is something odd, I'm not able to restart a stopped task, I tried to use 'clone and requeue' but after a while it is marked expired

**Comment by niphlod** [comment]
ok I got why a stopped task doesn't get executed if requeued. 
When you stop a task that is RUNNING, the status will be set as FAILED
If you stop a QUEUED task, stop_time is set to "now", the enabled bit is set to False and the status is set to STOPPED.
Now, let's get to the "requeue" feature.... it copies over the stop_time AND the enabled bit....so in the first case (running task that gets stopped) it works, but for the second case (a queued task that gets stopped) it doesn't....it's eventually marked as expired and it never gets executed.
The behaviour makes perfect sense for quite every task to be requeued, because to me a task that is STOPPED means a task that it got QUEUED by mistake. That being said, it's also true that if someone wants to clone and requeue a STOPPED task, he implicitly accepts that that task is not a mistake indeed and needs to be executed. I'm going to modify the requeue_task function to allow requeuing a STOPPED task, but that means that if a stop_time had been set originally, it won't be cloned, i.e. stop_task will be None.

**Comment by ilvalle** [comment]
I used to stop tasks across web2py updates before restarting the scheduler process otherwise after the scheduler restarted I will find a task 'RUNNING' but practically not really running.
For me 'clone and requeue' it is actually almost the same as restart/requeue, the only difference is that with the latter I will loose all the statistical information about all former executions. 
Can we add the 'requeue' option for STOPPED tasks and removing the 'stop task' button (since the task is already stopped) in the tast_details page?

**Comment by niphlod** [comment]
what's missing from the current implementation ? 

BTW: you'd better TERMINATE workers and wait for them to shutdown to achieve a consistent state between updates.... no need to fiddle with task's statuses at all.

**Comment by ilvalle** [comment]
In the current view of task_details the button 'stop task' for STOPPEDs
task is useless, I would replace it with 'requeue'

 Paolo

2014-05-04 22:27 GMT+02:00 niphlod notifications@github.com:
